### ISSUE TITLE
Plugin crashes on opening any sqf file

### ISSUE THREAD

**Issue by Fusselwurm** [Krzmbrzl/SQDev#93] opened 2016-08-11 20:08 UTC
Installed SQDev 0.6.1 into Eclipse 4.5.2 Build id: 20160218-0600 (Windows x64)

When opening an SQF file the plugin dies 

```
Plug-in "raven.sqdev.editors.sqfeditor" was unable to instantiate class "raven.sqdev.editors.sqfeditor.SQF_Editor"

....

Caused by: raven.sqdev.exceptions.BadSyntaxException: The command is not contained in the given input!
at raven.sqdev.syntax.Syntax.parseSyntax(Syntax.java:213)
```

 , for stack trace see: 
https://gist.github.com/Fusselwurm/8ce45b005823adb55c6a873f353218d5

**Comment by Krzmbrzl** [comment] 2016-08-12 06:42
Did you make a command update after installing the new version?

**Comment by Fusselwurm** [comment] 2016-08-12 19:36
No; it is a fresh install of both eclipse and this plugin

**Comment by Krzmbrzl** [comment] 2016-08-12 19:57
Did you have installed a previous version on this computer before?

However... Please try doing a command update and if this doesn't work, try to delete the plugin's resource directory and restart eclipse afterwards. You can find it in the [workspace directory](http://viralpatel.net/blogs/get-eclipse-current-workspace-path/) under _.metadata/.plugin_ and then delete the _raven.sqdev.util_ folder. (These folders might be hidden files)

**Comment by Fusselwurm** [comment] 2016-08-12 20:56
just to be sure: "command update" = "keyword update" ?

doesnt help any. the editor crashes even with empty sqf files, so there isant even a command that it could misinterpret

**Comment by Krzmbrzl** [comment] 2016-08-13 06:44
Yep that's what I meant (I think I should rename in the Plugin though) 

The editor does not have to contain any commands as it will load them on the start up in order to provide content assist. 

That's actually really weird. I can't reproduce it and as this crash also appears after having deleted the resource folder (then the Plugin will repopulate it with the default content that is tested) I'm actually unsure where this might come from. 

I will complete the referenced issues and then I'm going to send you a Dev-Version that should clarify what the problem  is...

**Comment by Krzmbrzl** [comment] 2016-08-13 06:46
Or even better... Could you go onto the resource folder and under _resources_ you'll find a file called  _Keywords.txt_... Please send me this file then I can have a look where it crashes

**Comment by Fusselwurm** [comment] 2016-08-13 08:21
@Krzmbrzl  http://xup.in/dl,62861679

**Comment by Krzmbrzl** [comment] 2016-08-13 15:15
Okay I found the issue: There's an error in the _SQFKeywords.txt_ for the command _addMagazine_.
Somehow there are misplaced newlines at that particular point in the file... I'm now investigating where they might come from. But as for now you can simply copy this file in the _resources_ folder of the plugin and everything should work fine (You can also copy it into the _backup_ folder in order to make it available as a reset)
https://www.dropbox.com/s/lns1a0wz8an513t/SQFKeywords.txt?dl=0

**Comment by Krzmbrzl** [comment] 2016-08-13 15:16
Are you running eclipse on windows or linux/Mac?

**Comment by Fusselwurm** [comment] 2016-08-13 16:14
Windows 10

**Comment by Fusselwurm** [comment] 2016-08-13 16:50
tried the attached keywords file. the error now is a different one: 

```
org.eclipse.core.runtime.AssertionFailedException: null argument:The given model may not be null!
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at raven.sqdev.editors.BasicFoldingManager.<init>(BasicFoldingManager.java:44)
	at raven.sqdev.editors.BasicCodeEditor.createManagers(BasicCodeEditor.java:419)
	at raven.sqdev.editors.BasicCodeEditor.createPartControl(BasicCodeEditor.java:261)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:99)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:572)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:536)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1163)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3252)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3167)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3149)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3144)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3108)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3089)
	at org.eclipse.ui.ide.IDE.openEditorOnFileStore(IDE.java:1159)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:97)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:70)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

```

**Comment by Krzmbrzl** [comment] 2016-08-13 16:50
Does the new file fix the problem? 

Okay then I'll have to check it on Win10 and see if the command update does this mistake on my machine as well

**Comment by Krzmbrzl** [comment] 2016-08-13 16:59
That's indeed something different... Shouldn't occur either though. 
Does it also occur on any opening of a SQF editor?

**Comment by Fusselwurm** [comment] 2016-08-13 18:28
oooh interesting. now the editor seems to work -- the mentioned exception seems to only happen when I do an "open file" on files that are not in the project dir.

**Comment by Krzmbrzl** [comment] 2016-08-13 22:07
Okay... At least that's sounding way better than before. I'll check that tomorrow

**Comment by Krzmbrzl** [comment] 2016-08-17 15:54
Allright I was able to reproduce the error (see #96).

As the original problem has been fixed (temporarily), I would close this issue if you don't mind.

**Comment by Fusselwurm** [comment] 2016-08-17 17:26
:+1:  thanks for your quick support :)

**Closed** 2016-08-17 18:22 UTC
Labels: crash
